# -*- coding: utf-8 -*-
"""inspect_columns.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4ZxN0GY0zjEEWyc-rH-GvU0u-rta0Kf
"""

def inspect_columns(df):
    """
    Prints dataset structure, dtypes, memory usage.
    """
    print("\n--- Dataset Overview ---")
    print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

    print("\nColumn Info:")
    print(df.dtypes)

    print("\nMemory Usage:")
    print(df.memory_usage(deep=True))

    print("\nFirst 3 Rows:")
    print(df.head(3))

    return df