# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxU-RxxjYCOXziu7LtjmA6v4hSEBp3V0
"""

import numpy as np
import pandas as pd
from numba import njit


# Numba-accelerated IQR function

@njit
def iqr_bounds(values):
    q1 = np.percentile(values, 25)
    q3 = np.percentile(values, 75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    return lower, upper


def detect_outliers(df: pd.DataFrame) -> pd.DataFrame:


    numeric_cols = df.select_dtypes(include=[np.number]).columns

    # If no numeric columns, return original
    if len(numeric_cols) == 0:
        print("No numeric columns found.")
        return df

    mask = np.ones(len(df), dtype=bool)

    for col in numeric_cols:
        col_values = df[col].dropna().values.astype(np.float64)

        # Skip empty columns
        if len(col_values) == 0:
            continue

        lower, upper = iqr_bounds(col_values)

        col_mask = (df[col] >= lower) & (df[col] <= upper)
        mask &= col_mask.fillna(True)  # keep NaNs

    removed_rows = len(df) - np.sum(mask)
    print(f"Removed {removed_rows} rows containing outliers.")

    return df[mask].reset_index(drop=True)